= Opalia Commons

This is a collection of common Scala code used by Opalia Systems.

Download new versions from the Git repository https://github.com/OpaliaSystems/opalia-commons.

=== Packages

* application: helper to create PID files
* codec: Base64 and Hex conversion
* configuration: Scala friendly helper for working with Typesafe configuration library
* crypto: helper for a simplified usage of MD5, SHA-256, SHA-384, SHA-512; AES, DES, 3DES; HMAC
* identifier: ID implementations (ObjectId, UUID)
* io: helper to assist with developing IO functionality
* net: types for a simplified working with networks
* number: some standard library improvements
* scripting: wrapper for Nashorn JavaScript engine; EJS (embedded JavaScript template engine)
* time: helper for a Scala friendly usage of java.time API

=== Usage in other SBT projects

Download this SBT project, change to the project directory and enter the following command:

[source,bash]
----
sbt publishLocal
----

Now this artifact can be used in your local SBT projects.

[source,scala]
----
libraryDependencies += "systems.opalia" %% "commons" % "<VERSION>"
----

=== License

Copyright (c) 2015 Eric Löffler

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

_http://www.apache.org/licenses/LICENSE-2.0_

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
